(require 'je-projectile)
(require 'je-magit)
(require 'je-org)
;;(require 'je-ivy)
(require 'je-helm)
(require 'je-treemacs)
(require 'je-lsp)
(require 'je-company)
(require 'je-elixir)
(require 'je-ocaml)
(require 'je-which-key)
(require 'je-undo-tree)


(provide 'je-modules)
